version: '3.8'

services:
  quizapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: faisalnybsys/react-quiz:1.0
    container_name: quizapp-production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped